server:
  port: 8769
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
      fail-fast: true
  profiles:
    active: native